version: '3'
services:
  opencti-dev-redis:
    container_name: opencti-dev-redis
    image: redis:7.0.4
    restart: unless-stopped
    ports:
      - 6379:6379
  opencti-dev-redis-insight:
    container_name: opencti-dev-redis-insight
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - 8001:8001
  opencti-dev-elasticsearch:
    container_name: opencti-dev-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
  opencti-dev-kibana:
    container_name: opencti-dev-kibana
    image: docker.elastic.co/kibana/kibana:8.3.3
    environment:
      - ELASTICSEARCH_HOSTS=http://opencti-dev-elasticsearch:9200
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - opencti-dev-elasticsearch
  opencti-dev-minio:
    container_name: opencti-dev-minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
      - "35300:35300"
    environment:
      MINIO_ROOT_USER: ChangeMe
      MINIO_ROOT_PASSWORD: ChangeMe
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
  opencti-dev-rabbitmq:
    container_name: opencti-dev-rabbitmq
    image: rabbitmq:3.11-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
  opencti-dev-jaegertracing:
    container_name: opencti-dev-jaegertracing
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686
      - 4318:4318
  worker:
    image: opencti/worker:5.7.1
    environment:
      - OPENCTI_URL=http://192.168.0.32:4000
      - OPENCTI_TOKEN=77af4679-5c82-4828-bd70-87b5222aad5a
      - WORKER_LOG_LEVEL=info
    network_mode: host
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  connector-import-file-stix:
    image: opencti/connector-import-file-stix:5.7.1
    environment:
      - OPENCTI_URL=http://192.168.0.32:4000
      - OPENCTI_TOKEN=77af4679-5c82-4828-bd70-87b5222aad5a
      - CONNECTOR_ID=importer-file-stix
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=false # Enable/disable auto-import of file
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    network_mode: host
    restart: always

volumes:
  elastic_search_data:
    external: true